export const dispatchData = [
  {
    additionalInfo: "Original pickup zip -Brookville, Pennsylvania, 15825",
    availableDate: "2025-01-08T00:00:00",
    createdDate: "2025-01-08T16:13:39.023797+00:00",
    destination: {
      city: "Leavenworth",
      geoCode: {
        latitude: 39.2758776,
        longitude: -94.99744609999999,
      },
      metroArea: "",
      state: "KS",
      zip: "66048",
    },
    digitalOffersEnabled: false,
    distance: 1059,
    expirationDate: "2025-01-22T00:00:00+00:00",
    hasInOpVehicle: false,
    hasPublicMarketplace: true,
    id: 300004645,
    isAutoAcceptEnabled: false,
    isBlocked: false,
    isPreferred: false,
    listingStatus: "LISTED",
    name: "d",
    origin: {
      city: "Harrisburg",
      geoCode: {
        latitude: 40.2741832,
        longitude: -76.8922729,
      },
      metroArea: "",
      state: "PA",
      zip: "17102",
    },
    preDispatchNotes: "",
    price: {
      balance: {
        amount: 0,
        balancePaymentMethod: "CASH",
        balancePaymentTermsBeginOn: "PICKUP",
        paymentTime: "IMMEDIATELY",
      },
      cod: {
        amount: 610,
        paymentLocation: "DELIVERY",
        paymentMethod: "CASH_CERTIFIED_FUNDS",
      },
      total: 610,
    },
    shipper: {
      companyName: "Loadmaster Group  Inc",
      customerId: "d2a444a8-909d-4238-bcfc-cfb7a3b5760c",
      email: "dispatch@loadmg.com",
      hoursOfOperation: "M-Sun 8-11",
      hqTimeZone: "EST",
      numberOfRatings: 47,
      overallRating: {
        averageRating: 4.9,
        totalAmount: 874,
      },
      phone: "740-400-0044",
      rating: 100,
      tierGroup: "Broker",
    },
    shipperOrderId: "SC-007963DDD",
    sortingDate: {},
    trailerType: "OPEN",
    vehicles: [
      {
        additionalInfo: "",
        color: "",
        id: "022007e2-abea-498d-a647-13e937741c9f",
        licensePlate: "",
        licensePlateState: "",
        lotNumber: "",
        make: "Ford",
        model: "F-150",
        qty: 1,
        shippingSpecs: {
          height: 0,
          length: 0,
          weight: 0,
          width: 0,
        },
        vehicleType: "PICKUP",
        vehicleTypeOther: "",
        wideLoad: false,
        year: 2021,
      },
    ],
  },
  {
    additionalInfo: "2139332623   inop requires winch storage to residence",
    availableDate: "2025-01-08T00:00:00",
    createdDate: "2025-01-08T16:17:53Z",
    destination: {
      city: "Palatine",
      geoCode: {
        latitude: 42.101302,
        longitude: -88.067728,
      },
      metroArea: "Chicago - Naperville - Joliet",
      state: "IL",
      zip: "60067",
    },
    digitalOffersEnabled: false,
    distance: 737,
    expirationDate: "2025-02-07T08:00:00Z",
    hasInOpVehicle: true,
    hasPublicMarketplace: true,
    id: 115456875,
    isAutoAcceptEnabled: false,
    isBlocked: false,
    isPreferred: false,
    listingStatus: "LISTED",
    name: "d",
    origin: {
      city: "White Haven",
      geoCode: {
        latitude: 41.09918,
        longitude: -75.736394,
      },
      metroArea: "Scranton - Wilkes-Barre",
      state: "PA",
      zip: "18661",
    },
    preDispatchNotes: "",
    price: {
      balance: {
        amount: 0,
      },
      cod: {
        amount: 500,
        paymentLocation: "DELIVERY",
        paymentMethod: "CASH_CERTIFIED_FUNDS",
      },
      total: 500,
    },
    shipper: {
      companyName: "Bionic Logistic Solutions LLC",
      customerId: "6b874fad-7a31-4e4b-a512-9e86041b21b8",
      email: "support@bioniclogisticsolutions.com",
      hoursOfOperation: "24/7",
      hqTimeZone: "PST",
      numberOfRatings: 0,
      overallRating: {
        averageRating: 5,
        totalAmount: 163,
      },
      phone: "(323) 856-1687",
      rating: 0,
      tierGroup: "Broker",
    },
    shipperOrderId: "19627580",
    sortingDate: {},
    trailerType: "OPEN",
    vehicles: [
      {
        additionalInfo: "1996 Subaru Impreza outback wagon",
        externalVehicleId: "",
        id: "181908373",
        make: "Subaru",
        model: "outback wagon",
        qty: 1,
        vehicleType: "CAR",
        wideLoad: false,
        year: 1996,
      },
    ],
  },
];

// {
//   additionalInfo: "2139332623   inop requires winch storage to residence",
//   availableDate: "2025-01-08T00:00:00",
//   createdDate: "2025-01-08T16:17:53Z",
//   destination: {
//     city: "Palatine",
//     geoCode: {
//       latitude: 42.101302,
//       longitude: -88.067728,
//     },
//     metroArea: "Chicago - Naperville - Joliet",
//     state: "IL",
//     zip: "60067",
//   },
//   digitalOffersEnabled: false,
//   distance: 737,
//   expirationDate: "2025-02-07T08:00:00Z",
//   hasInOpVehicle: true,
//   hasPublicMarketplace: true,
//   id: 115456875,
//   isAutoAcceptEnabled: false,
//   isBlocked: false,
//   isPreferred: false,
//   listingStatus: "LISTED",
//   name: "d",
//   origin: {
//     city: "White Haven",
//     geoCode: {
//       latitude: 41.09918,
//       longitude: -75.736394,
//     },
//     metroArea: "Scranton - Wilkes-Barre",
//     state: "PA",
//     zip: "18661",
//   },
//   preDispatchNotes: "",
//   price: {
//     balance: {
//       amount: 0,
//     },
//     cod: {
//       amount: 500,
//       paymentLocation: "DELIVERY",
//       paymentMethod: "CASH_CERTIFIED_FUNDS",
//     },
//     total: 500,
//   },
//   shipper: {
//     companyName: "Bionic Logistic Solutions LLC",
//     customerId: "6b874fad-7a31-4e4b-a512-9e86041b21b8",
//     email: "support@bioniclogisticsolutions.com",
//     hoursOfOperation: "24/7",
//     hqTimeZone: "PST",
//     numberOfRatings: 0,
//     overallRating: {
//       averageRating: 5,
//       totalAmount: 163,
//     },
//     phone: "(323) 856-1687",
//     rating: 0,
//     tierGroup: "Broker",
//   },
//   shipperOrderId: "19627580",
//   sortingDate: {},
//   trailerType: "OPEN",
//   vehicles: [
//     {
//       additionalInfo: "1996 Subaru Impreza outback wagon",
//       externalVehicleId: "",
//       id: "181908373",
//       make: "Subaru",
//       model: "outback wagon",
//       qty: 1,
//       vehicleType: "CAR",
//       wideLoad: false,
//       year: 1996,
//     },
//   ],
// },

// {
//   additionalInfo: "2139332623   inop requires winch storage to residence",
//   availableDate: "2025-01-08T00:00:00",
//   createdDate: "2025-01-08T16:17:53Z",
//   destination: {
//     city: "Palatine",
//     geoCode: {
//       latitude: 42.101302,
//       longitude: -88.067728,
//     },
//     metroArea: "Chicago - Naperville - Joliet",
//     state: "IL",
//     zip: "60067",
//   },
//   digitalOffersEnabled: false,
//   distance: 737,
//   expirationDate: "2025-02-07T08:00:00Z",
//   hasInOpVehicle: true,
//   hasPublicMarketplace: true,
//   id: 115456875,
//   isAutoAcceptEnabled: false,
//   isBlocked: false,
//   isPreferred: false,
//   listingStatus: "LISTED",
//   name: "d",
//   origin: {
//     city: "White Haven",
//     geoCode: {
//       latitude: 41.09918,
//       longitude: -75.736394,
//     },
//     metroArea: "Scranton - Wilkes-Barre",
//     state: "PA",
//     zip: "18661",
//   },
//   preDispatchNotes: "",
//   price: {
//     balance: {
//       amount: 0,
//     },
//     cod: {
//       amount: 500,
//       paymentLocation: "DELIVERY",
//       paymentMethod: "CASH_CERTIFIED_FUNDS",
//     },
//     total: 500,
//   },
//   shipper: {
//     companyName: "Bionic Logistic Solutions LLC",
//     customerId: "6b874fad-7a31-4e4b-a512-9e86041b21b8",
//     email: "support@bioniclogisticsolutions.com",
//     hoursOfOperation: "24/7",
//     hqTimeZone: "PST",
//     numberOfRatings: 0,
//     overallRating: {
//       averageRating: 5,
//       totalAmount: 163,
//     },
//     phone: "(323) 856-1687",
//     rating: 0,
//     tierGroup: "Broker",
//   },
//   shipperOrderId: "19627580",
//   sortingDate: {},
//   trailerType: "OPEN",
//   vehicles: [
//     {
//       additionalInfo: "1996 Subaru Impreza outback wagon",
//       externalVehicleId: "",
//       id: "181908373",
//       make: "Subaru",
//       model: "outback wagon",
//       qty: 1,
//       vehicleType: "CAR",
//       wideLoad: false,
//       year: 1996,
//     },
//   ],
// },

// {
//   additionalInfo: "2139332623   inop requires winch storage to residence",
//   availableDate: "2025-01-08T00:00:00",
//   createdDate: "2025-01-08T16:17:53Z",
//   destination: {
//     city: "Palatine",
//     geoCode: {
//       latitude: 42.101302,
//       longitude: -88.067728,
//     },
//     metroArea: "Chicago - Naperville - Joliet",
//     state: "IL",
//     zip: "60067",
//   },
//   digitalOffersEnabled: false,
//   distance: 737,
//   expirationDate: "2025-02-07T08:00:00Z",
//   hasInOpVehicle: true,
//   hasPublicMarketplace: true,
//   id: 115456875,
//   isAutoAcceptEnabled: false,
//   isBlocked: false,
//   isPreferred: false,
//   listingStatus: "LISTED",
//   name: "d",
//   origin: {
//     city: "White Haven",
//     geoCode: {
//       latitude: 41.09918,
//       longitude: -75.736394,
//     },
//     metroArea: "Scranton - Wilkes-Barre",
//     state: "PA",
//     zip: "18661",
//   },
//   preDispatchNotes: "",
//   price: {
//     balance: {
//       amount: 0,
//     },
//     cod: {
//       amount: 500,
//       paymentLocation: "DELIVERY",
//       paymentMethod: "CASH_CERTIFIED_FUNDS",
//     },
//     total: 500,
//   },
//   shipper: {
//     companyName: "Bionic Logistic Solutions LLC",
//     customerId: "6b874fad-7a31-4e4b-a512-9e86041b21b8",
//     email: "support@bioniclogisticsolutions.com",
//     hoursOfOperation: "24/7",
//     hqTimeZone: "PST",
//     numberOfRatings: 0,
//     overallRating: {
//       averageRating: 5,
//       totalAmount: 163,
//     },
//     phone: "(323) 856-1687",
//     rating: 0,
//     tierGroup: "Broker",
//   },
//   shipperOrderId: "19627580",
//   sortingDate: {},
//   trailerType: "OPEN",
//   vehicles: [
//     {
//       additionalInfo: "1996 Subaru Impreza outback wagon",
//       externalVehicleId: "",
//       id: "181908373",
//       make: "Subaru",
//       model: "outback wagon",
//       qty: 1,
//       vehicleType: "CAR",
//       wideLoad: false,
//       year: 1996,
//     },
//   ],
// },

// {
//   additionalInfo: "2139332623   inop requires winch storage to residence",
//   availableDate: "2025-01-08T00:00:00",
//   createdDate: "2025-01-08T16:17:53Z",
//   destination: {
//     city: "Palatine",
//     geoCode: {
//       latitude: 42.101302,
//       longitude: -88.067728,
//     },
//     metroArea: "Chicago - Naperville - Joliet",
//     state: "IL",
//     zip: "60067",
//   },
//   digitalOffersEnabled: false,
//   distance: 737,
//   expirationDate: "2025-02-07T08:00:00Z",
//   hasInOpVehicle: true,
//   hasPublicMarketplace: true,
//   id: 115456875,
//   isAutoAcceptEnabled: false,
//   isBlocked: false,
//   isPreferred: false,
//   listingStatus: "LISTED",
//   name: "d",
//   origin: {
//     city: "White Haven",
//     geoCode: {
//       latitude: 41.09918,
//       longitude: -75.736394,
//     },
//     metroArea: "Scranton - Wilkes-Barre",
//     state: "PA",
//     zip: "18661",
//   },
//   preDispatchNotes: "",
//   price: {
//     balance: {
//       amount: 0,
//     },
//     cod: {
//       amount: 500,
//       paymentLocation: "DELIVERY",
//       paymentMethod: "CASH_CERTIFIED_FUNDS",
//     },
//     total: 500,
//   },
//   shipper: {
//     companyName: "Bionic Logistic Solutions LLC",
//     customerId: "6b874fad-7a31-4e4b-a512-9e86041b21b8",
//     email: "support@bioniclogisticsolutions.com",
//     hoursOfOperation: "24/7",
//     hqTimeZone: "PST",
//     numberOfRatings: 0,
//     overallRating: {
//       averageRating: 5,
//       totalAmount: 163,
//     },
//     phone: "(323) 856-1687",
//     rating: 0,
//     tierGroup: "Broker",
//   },
//   shipperOrderId: "19627580",
//   sortingDate: {},
//   trailerType: "OPEN",
//   vehicles: [
//     {
//       additionalInfo: "1996 Subaru Impreza outback wagon",
//       externalVehicleId: "",
//       id: "181908373",
//       make: "Subaru",
//       model: "outback wagon",
//       qty: 1,
//       vehicleType: "CAR",
//       wideLoad: false,
//       year: 1996,
//     },
//   ],
// },
