export const dispatchData = [
  {
    additionalInfo: "Original pickup zip -Brookville, Pennsylvania, 15825",
    availableDate: "2025-01-08T00:00:00",
    createdDate: "2025-01-08T16:13:39.023797+00:00",
    destination: {
      city: "Leavenworth",
      geoCode: {
        latitude: 39.2758776,
        longitude: -94.99744609999999,
      },
      metroArea: "",
      state: "KS",
      zip: "66048",
    },
    digitalOffersEnabled: false,
    distance: 1059,
    expirationDate: "2025-01-22T00:00:00+00:00",
    hasInOpVehicle: false,
    hasPublicMarketplace: true,
    id: 300004645,
    isAutoAcceptEnabled: false,
    isBlocked: false,
    isPreferred: false,
    listingStatus: "LISTED",
    name: "d",
    origin: {
      city: "Harrisburg",
      geoCode: {
        latitude: 40.2741832,
        longitude: -76.8922729,
      },
      metroArea: "",
      state: "PA",
      zip: "17102",
    },
    preDispatchNotes: "",
    price: {
      balance: {
        amount: 0,
        balancePaymentMethod: "CASH",
        balancePaymentTermsBeginOn: "PICKUP",
        paymentTime: "IMMEDIATELY",
      },
      cod: {
        amount: 610,
        paymentLocation: "DELIVERY",
        paymentMethod: "CASH_CERTIFIED_FUNDS",
      },
      total: 610,
    },
    shipper: {
      companyName: "Loadmaster Group  Inc",
      customerId: "d2a444a8-909d-4238-bcfc-cfb7a3b5760c",
      email: "dispatch@loadmg.com",
      hoursOfOperation: "M-Sun 8-11",
      hqTimeZone: "EST",
      numberOfRatings: 47,
      overallRating: {
        averageRating: 4.9,
        totalAmount: 874,
      },
      phone: "740-400-0044",
      rating: 100,
      tierGroup: "Broker",
    },
    shipperOrderId: "SC-007963DDD",
    sortingDate: {},
    trailerType: "OPEN",
    vehicles: [
      {
        additionalInfo: "",
        color: "",
        id: "022007e2-abea-498d-a647-13e937741c9f",
        licensePlate: "",
        licensePlateState: "",
        lotNumber: "",
        make: "Ford",
        model: "F-150",
        qty: 1,
        shippingSpecs: {
          height: 0,
          length: 0,
          weight: 0,
          width: 0,
        },
        vehicleType: "PICKUP",
        vehicleTypeOther: "",
        wideLoad: false,
        year: 2021,
      },
    ],
  },
  {
    additionalInfo: "2139332623   inop requires winch storage to residence",
    availableDate: "2025-01-08T00:00:00",
    createdDate: "2025-01-08T16:17:53Z",
    destination: {
      city: "Palatine",
      geoCode: {
        latitude: 42.101302,
        longitude: -88.067728,
      },
      metroArea: "Chicago - Naperville - Joliet",
      state: "IL",
      zip: "60067",
    },
    digitalOffersEnabled: false,
    distance: 737,
    expirationDate: "2025-02-07T08:00:00Z",
    hasInOpVehicle: true,
    hasPublicMarketplace: true,
    id: 115456875,
    isAutoAcceptEnabled: false,
    isBlocked: false,
    isPreferred: false,
    listingStatus: "LISTED",
    name: "d",
    origin: {
      city: "White Haven",
      geoCode: {
        latitude: 41.09918,
        longitude: -75.736394,
      },
      metroArea: "Scranton - Wilkes-Barre",
      state: "PA",
      zip: "18661",
    },
    preDispatchNotes: "",
    price: {
      balance: {
        amount: 0,
      },
      cod: {
        amount: 500,
        paymentLocation: "DELIVERY",
        paymentMethod: "CASH_CERTIFIED_FUNDS",
      },
      total: 500,
    },
    shipper: {
      companyName: "Bionic Logistic Solutions LLC",
      customerId: "6b874fad-7a31-4e4b-a512-9e86041b21b8",
      email: "support@bioniclogisticsolutions.com",
      hoursOfOperation: "24/7",
      hqTimeZone: "PST",
      numberOfRatings: 0,
      overallRating: {
        averageRating: 5,
        totalAmount: 163,
      },
      phone: "(323) 856-1687",
      rating: 0,
      tierGroup: "Broker",
    },
    shipperOrderId: "19627580",
    sortingDate: {},
    trailerType: "OPEN",
    vehicles: [
      {
        additionalInfo: "1996 Subaru Impreza outback wagon",
        externalVehicleId: "",
        id: "181908373",
        make: "Subaru",
        model: "outback wagon",
        qty: 1,
        vehicleType: "CAR",
        wideLoad: false,
        year: 1996,
      },
    ],
  },
  {
    additionalInfo: "Must be picked up before 5 PM, storage yard location",
    availableDate: "2025-02-02T00:00:00",
    createdDate: "2025-02-01T14:30:00Z",
    destination: {
      city: "Austin",
      geoCode: {
        latitude: 30.267153,
        longitude: -97.743057,
      },
      metroArea: "Austin-Round Rock",
      state: "TX",
      zip: "73301",
    },
    digitalOffersEnabled: true,
    distance: 1350,
    expirationDate: "2025-02-15T00:00:00Z",
    hasInOpVehicle: false,
    hasPublicMarketplace: true,
    id: 789654123,
    isAutoAcceptEnabled: false,
    isBlocked: false,
    isPreferred: false,
    listingStatus: "LISTED",
    name: "d",
    origin: {
      city: "Miami",
      geoCode: {
        latitude: 25.7617,
        longitude: -80.1918,
      },
      metroArea: "Miami-Fort Lauderdale",
      state: "FL",
      zip: "33101",
    },
    preDispatchNotes: "Vehicle is running and ready for transport.",
    price: {
      balance: {
        amount: 200,
        balancePaymentMethod: "CASH",
        balancePaymentTermsBeginOn: "PICKUP",
        paymentTime: "IMMEDIATELY",
      },
      cod: {
        amount: 750,
        paymentLocation: "DELIVERY",
        paymentMethod: "CASH_CERTIFIED_FUNDS",
      },
      total: 950,
    },
    shipper: {
      companyName: "Elite Auto Transport LLC",
      customerId: "a8c7d9f5-1b2c-4d8f-8e9b-7e6d5f4c3a2b",
      email: "dispatch@eliteautotransport.com",
      hoursOfOperation: "M-F 9-6, Sat 10-4",
      hqTimeZone: "EST",
      numberOfRatings: 120,
      overallRating: {
        averageRating: 4.8,
        totalAmount: 3200,
      },
      phone: "(305) 555-1234",
      rating: 98,
      tierGroup: "Broker",
    },
    shipperOrderId: "EA-456789",
    sortingDate: {},
    trailerType: "ENCLOSED",
    vehicles: [
      {
        additionalInfo: "",
        color: "Black",
        id: "025f7e3b-91a4-45b5-bcf2-912f3e7850b4",
        licensePlate: "",
        licensePlateState: "",
        lotNumber: "",
        make: "Tesla",
        model: "Model S",
        qty: 1,
        shippingSpecs: {
          height: 56,
          length: 196,
          weight: 4647,
          width: 77,
        },
        vehicleType: "CAR",
        vehicleTypeOther: "",
        wideLoad: false,
        year: 2023,
      },
    ],
  },
  {
    additionalInfo: "Pickup from dealership, ready after 10 AM",
    availableDate: "2025-02-03T00:00:00",
    createdDate: "2025-02-02T10:45:00Z",
    destination: {
      city: "Denver",
      geoCode: {
        latitude: 39.739236,
        longitude: -104.990251,
      },
      metroArea: "Denver-Aurora",
      state: "CO",
      zip: "80202",
    },
    digitalOffersEnabled: false,
    distance: 920,
    expirationDate: "2025-02-10T00:00:00Z",
    hasInOpVehicle: false,
    hasPublicMarketplace: true,
    id: 456987321,
    isAutoAcceptEnabled: false,
    isBlocked: false,
    isPreferred: false,
    listingStatus: "LISTED",
    name: "d",
    origin: {
      city: "Dallas",
      geoCode: {
        latitude: 32.7767,
        longitude: -96.797,
      },
      metroArea: "Dallas-Fort Worth",
      state: "TX",
      zip: "75201",
    },
    preDispatchNotes: "Vehicle is brand new, dealership pickup.",
    price: {
      balance: {
        amount: 100,
        balancePaymentMethod: "CASH",
        balancePaymentTermsBeginOn: "PICKUP",
        paymentTime: "IMMEDIATELY",
      },
      cod: {
        amount: 650,
        paymentLocation: "DELIVERY",
        paymentMethod: "CASH_CERTIFIED_FUNDS",
      },
      total: 750,
    },
    shipper: {
      companyName: "Premier Auto Logistics",
      customerId: "5d9a1f3e-2c4b-4f7d-92f8-1e3a5b6c7d8e",
      email: "dispatch@premierautologistics.com",
      hoursOfOperation: "M-F 8-7, Sat 9-3",
      hqTimeZone: "CST",
      numberOfRatings: 85,
      overallRating: {
        averageRating: 4.7,
        totalAmount: 2900,
      },
      phone: "(214) 555-5678",
      rating: 95,
      tierGroup: "Broker",
    },
    shipperOrderId: "PA-987654",
    sortingDate: {},
    trailerType: "OPEN",
    vehicles: [
      {
        additionalInfo: "2024 Mercedes-Benz GLC 300",
        color: "White",
        id: "b9d7a3e2-45f1-4c8b-ae6d-1f7c9e3b5a2d",
        licensePlate: "",
        licensePlateState: "",
        lotNumber: "",
        make: "Mercedes-Benz",
        model: "GLC 300",
        qty: 1,
        shippingSpecs: {
          height: 64,
          length: 185,
          weight: 3935,
          width: 74,
        },
        vehicleType: "SUV",
        vehicleTypeOther: "",
        wideLoad: false,
        year: 2024,
      },
    ],
  },
];
